# Generated by Django 5.0 on 2025-10-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
        ('movies', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='movie_data',
            field=models.ManyToManyField(to='movies.movie'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Georgia', max_length=16),
        ),
    ]
