# Generated by Django 5.0 on 2025-10-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_movie_data_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='movie_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(default='Georgia', max_length=16),
        ),
    ]
